Fixes wrong characters being used as dbtable prefix on the mac
(when using MacOS Big Sur 11.6)
The output of `start.sh` (after a full clean) was:
Error: Error: `$table_prefix` in `wp-config.php` can only contain numbers, letters, and underscores.